import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // App guides sidebar
  appGuidesSidebar: [
    {
      type: 'category',
      label: 'App Guides',
      items: [
        'app-guides/app-overview',
      ],
    },
  ],

  // Game guides sidebar
  gameGuidesSidebar: [
    {
      type: 'category',
      label: 'Flight Simulation',
      items: [
        'game-guides/dcs-world/windows',
        'game-guides/il2-sturmovik/windows',
        'game-guides/microsoft-flight-simulator-2020/windows',
      ],
    },
    {
      type: 'category',
      label: 'Space Simulation',
      items: [
        'game-guides/elite-dangerous/windows',
      ],
    },
    {
      type: 'category',
      label: 'FPS Games',
      items: [
        'game-guides/counter-strike-2/linux',
      ],
    },
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
